---
title: "Assignment 0: Reproducible Quarto Document"
author: "Nia Martinez Jaime"
format: html
editor: visual
---

```{r}
#| echo: false

# Two solutions
a <- 1
b <- 3
c <- 2

# One solution
# a <- 1
# b <- -6
# c <- 9

# No solutions
# a <- 1
# b <- 2
# c <- 5

```

The plot below show the curve of $f(x) = `r a`x^2 + `r b`x + `r c`$.

```{r}
#| echo: false
#| warning: false

x <- seq(-5,5, length = 300)
y <- a*x^2 + b*x + c

plot(x,y, main = paste0("Solve ", a, "x^2 + ", b, "x + ", c, " = 0"), type = "l")
abline(h=0, col = "forestgreen")

sol1 <- (-1*b + sqrt(b^2-4*a*c))/2*a

sol2 <- (-1*b - sqrt(b^2-4*a*c))/2*a


sol <- ifelse(sol1 == "NaN" & sol2 == "NaN", "The quadratic equation does not have a solution solving:",
              ifelse(sol1 != sol2, paste0("The solution of the quadratic equation is x = (", min(c(sol1,sol2)), ", ", max(c(sol1, sol2)), ") which was solved using:"),
                     ifelse(sol1 == sol2, paste0("The solution of the quadratic equation is x = ", sol1, " which was solved using:"), "No Solution")))

```

`r sol`

$$\frac{-(`r b`) \pm \sqrt{(`r b`)^2-4*(`r a`)*(`r c`)}}{2*(`r a`)}$$
